/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EditorRouteImport } from './routes/editor'
import { Route as GlosarRouteImport } from './routes/glosar'
import { Route as ImportRouteImport } from './routes/import'
import { Route as NavrhyRouteImport } from './routes/navrhy'
import { Route as VydaniRouteImport } from './routes/vydani'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorRoute = EditorRouteImport.update({
  id: '/editor',
  path: '/editor',
  getParentRoute: () => rootRouteImport,
} as any)
const GlosarRoute = GlosarRouteImport.update({
  id: '/glosar',
  path: '/glosar',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportRoute = ImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => rootRouteImport,
} as any)
const NavrhyRoute = NavrhyRouteImport.update({
  id: '/navrhy',
  path: '/navrhy',
  getParentRoute: () => rootRouteImport,
} as any)
const VydaniRoute = VydaniRouteImport.update({
  id: '/vydani',
  path: '/vydani',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/editor': typeof EditorRoute
  '/glosar': typeof GlosarRoute
  '/import': typeof ImportRoute
  '/navrhy': typeof NavrhyRoute
  '/vydani': typeof VydaniRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/editor': typeof EditorRoute
  '/glosar': typeof GlosarRoute
  '/import': typeof ImportRoute
  '/navrhy': typeof NavrhyRoute
  '/vydani': typeof VydaniRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/editor': typeof EditorRoute
  '/glosar': typeof GlosarRoute
  '/import': typeof ImportRoute
  '/navrhy': typeof NavrhyRoute
  '/vydani': typeof VydaniRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/editor' | '/glosar' | '/import' | '/navrhy' | '/vydani'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/editor' | '/glosar' | '/import' | '/navrhy' | '/vydani'
  id:
    '__root__' | '/' | '/editor' | '/glosar' | '/import' | '/navrhy' | '/vydani'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EditorRoute: typeof EditorRoute
  GlosarRoute: typeof GlosarRoute
  ImportRoute: typeof ImportRoute
  NavrhyRoute: typeof NavrhyRoute
  VydaniRoute: typeof VydaniRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editor': {
      id: '/editor'
      path: '/editor'
      fullPath: '/editor'
      preLoaderRoute: typeof EditorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/glosar': {
      id: '/glosar'
      path: '/glosar'
      fullPath: '/glosar'
      preLoaderRoute: typeof GlosarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import': {
      id: '/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof ImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/navrhy': {
      id: '/navrhy'
      path: '/navrhy'
      fullPath: '/navrhy'
      preLoaderRoute: typeof NavrhyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vydani': {
      id: '/vydani'
      path: '/vydani'
      fullPath: '/vydani'
      preLoaderRoute: typeof VydaniRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EditorRoute: EditorRoute,
  GlosarRoute: GlosarRoute,
  ImportRoute: ImportRoute,
  NavrhyRoute: NavrhyRoute,
  VydaniRoute: VydaniRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
